setopt APPEND_HISTORY
setopt BASH_AUTO_LIST
setopt COMPLETE_IN_WORD
setopt CORRECT
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt SUN_KEYBOARD_HACK

unsetopt AUTO_LIST
unsetopt BEEP
unsetopt CLOBBER
unsetopt LIST_BEEP

HISTSIZE=65536
HISTFILE=~/.zsh_history
SAVEHIST=65536

MANPATH="${MANPATH}:/usr/local/share/man"
